name: NoLagg
main: com.bergerkiller.bukkit.nolagg.NoLagg
version: 1.89.4
author: bergerkiller
authors: [bergerkiller, lenis0012]
load: startup
depend: [BKCommonLib]
description: Plugin that prevents server lag caused by all sorts of events, from tnt to item drop spam
commands:
    nolagg:
        description: The general command of NoLagg
        aliases: [lag, nl]
        usage: /lag [args...]